# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJ2NAjp5r5sq_9NlVPYo0nyKOHC7fwut
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# DataFrame yaratish
data = {
    'Yil': [2018, 2019, 2020, 2021, 2022],
    'Sotuvlar': [150, 200, 250, 300, 350],
    'Xarajatlar': [100, 150, 180, 200, 220]
}

df = pd.DataFrame(data)

# Asosiy statistika
print(df.describe())

# Grafik chizish
plt.figure(figsize=(10, 6))
plt.plot(df['Yil'], df['Sotuvlar'], label='Sotuvlar', marker='o')
plt.plot(df['Yil'], df['Xarajatlar'], label='Xarajatlar', marker='o')

plt.title('Sotuvlar va Xarajatlar bo\'yicha tahlil')
plt.xlabel('Yil')
plt.ylabel('Qiymatlar')
plt.legend()
plt.grid(True)
plt.show()